deploymentApiVersion: apps/v1
replicaCount: 1
strategyType: RollingUpdate
service:
  externalPort: 80
  internalPort: 80
prometheus:
  metrics: true
postgresql:
  enabled: false
ingress:
  modSecurity:
    enabled: true
    secRuleEngine: "DetectionOnly"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
podAnnotations: { app.gitlab.com/app: gametactic-room }
